### PR TITLE
Add a sample movie 'Big Buck Bunny'

### PR DESCRIPTION
**Pull request by yoshi-ogawa**
Add a new sample movie file which is commonly used to test video playback. And add a README to show information about the movie.

Hi @djusdekd  and @tdhung 
I would like to add a new sample movie called 'Big Buck Bunny' to this repository.
It is commonly used to test video playback, and I have a plan to use this movie in a demonstration program for RZ/G2L Linux.

### CODE REVIEW

**Review by djusdekd — COMMENTED** [review]
Hello @yoshi-ogawa,
I check your PR and I not see any issue.

Hello @tdhung,
Can we approve this PR?

Thank you

**Comment by tdhung** [comment]
Hi @yoshi-ogawa, @djusdekd,
It's OK for submit video here, but you should consider to use original video (and put download link here) if it's already available somewhere else.
In this case you add Big Bug Bunny, with enough credit and license info, so it is acceptable. But you can simply use the original video unless you really need to cut the video time to 30s.
And one more point: the video is 24fps, not 30fps like the name claimed. Original Big Bug Bunny video is 24fps, and your ffmpeg command only cut video time, not change the fps.

**Comment by yoshi-ogawa** [comment]
Hi @tdhung and @djusdekd ,
Thank you for checking.

> It's OK for submit video here, but you should consider to use original video (and put download link here) if it's already available somewhere else.
In this case you add Big Bug Bunny, with enough credit and license info, so it is acceptable. But you can simply use the original video unless you really need to cut the video time to 30s.

I intended that the sample movie is used for demonstration software. I uploaded the actual movie file to the repository so that we can download the movie by describing a Yocto recipe. Since the original video is too big (over 700MB) to install root filesystem, I cut the video to 30 sec.

> And one more point: the video is 24fps, not 30fps like the name claimed. Original Big Bug Bunny video is 24fps, and your ffmpeg command only cut video time, not change the fps.

I fixed the sample movie and ffmpeg command in the README.

Thank you

**Comment by tdhung** [comment]
Hi @yoshi-ogawa and @djusdekd,
I approved and merged.

**Pull request merged**
